pay.analytics.job.runHour=mdf.arg.run-hour
pay.analytics.job.runDate=mdf.arg.run-date
pay.analytics.job.minute=mdf.arg.run-minute
pay.analytics.job.preprocess.filecheck.enabled=mdf.data.defaults.files.check.enabled
pay.analytics.job.postprocess.filecheck.enabled=mdf.data.defaults.files.check.enabled
pay.analytics.job.save.mode=mdf.data.defaults.files.save-mode
pay.analytics.job.save.mode.check.enabled=mdf.data.defaults.files.check.enabled
pay.analytics.job.iceberg.optimization.enabled=mdf.data.defaults.optimization
pay.analytics.job.jhi.publish.enabled=mdf.arg.enable-jhi
pay.analytics.module.name=mdf.service.config.module
pay.analytics.job.name=mdf.platform.app-name
pay.analytics.job.publish.table.info.enabled=mdf.table-info-publisher.enabled
pay.analytics.conf.file.name=mdf.config.conf-file-type
pay.analytics.cumulative.start.date=mdf.arg.cumulative-start-date
spark.pie.hadoop.config.service.cluster.name=mdf.data.defaults.paths.cluster-name
pay.analytics.env=mdf.platform.env
pay.analytics.project=mdf.service.config.project
pay.analytics.default.rest.end.point=mdf.table-info-publisher.endpoint
pay.analytics.sink.options=mdf.data.defaults.spark-options
pay.analytics.a3.token.ttl=mdf.service.idms.token-ttl
pay.analytics.iceberg.sink.type=mdf.sinks.type
pay.ss.table.properties=mdf.iceberg-table-properties
spark.sql.catalog.local.type=mdf.sinks.catalog-name
pay.analytics.table.optimization.options=mdf.data.tables.iceberg-table-write-properties
pay.analytics.grace.period=mdf.data.deafults.path.grace-period
pay.analytics.jhi.end.point=mdf.jhi.end-points.service
pay.analytics.lob=mdf.jhi.lob
pay.analytics.lob.contact.email=mdf.jhi.contact
pay.analytics.jhi.register.api=mdf.jhi.url.createUrl
pay.analytics.jhi.update.api=mdf.jhi.url.updateUrl
pay.analytics.jhi.fetch.api=mdf.jhi.url.readUrl
pay.analytics.notification.service.end.point=mdf.notification.email.endpoint
IPLocation=mdf.data.sources.default.path
IPPattern=mdf.data.sources.default.pattern
AppName=mdf.platform.app-name
OPLocation=unsupported
Frequency=mdf.batch.frequency
module=mdf.wpc.module
PreProcessFileLocation=unsupported
PreProcessCheckType=mdf.data.sources.check.control-file-type
PreProcessFileCount=mdf.data.sources.check.file-count
PostProcessFileLocation=mdf.data.sinks.check.path
PostProcessFileType=mdf.data.sources.check.file-type
preProcessFileCheckEnabled=unsupported
postProcessFileCheckEnabled=unsupported
FileSaveMode=mdf.sinks.save-mode
IPType=unsupported
OPType=unsupported
IPDatabase=mdf.sources.defalut.db-type
IPTableName=mdf.sources.default.table-name
IPDBUserName=mdf.sources.default.db-user
IPDBPassword=mdf.sources.default.db-password
IPDBUrl=mdf.sources.default.db-url
OPDatabase=mdf.sinks.default.db-type
OPTableName=mdf.sinks.default.table-name
OPDBUserName=mdf.sinks.default.db-user
OPDBPassword=mdf.sinks.default.db-password
OPDBUrl=mdf.sinks.default.db-url
ReportingPartitionColumn=mdf.sinks.default.partition-columns
OPStorageLocation=mdf.sinks.default.storage-location
OPPartitionColumn=mdf.sinks.default.partition-columns
OPSortColumn=mdf.sinks.default.sort-columns
OPDistributionType=mdf.sinks.default.dist-type
IPDatePattern=mdf.data.source.default.date-pattern
OPDatePattern=mdf.data.sink.default.date-pattern
SlidingWindow=mdf.data.deafults.path.sliding-window
PublishToJhiEnabled=wpc-mdf.jhi.jhiPublishEnabled
JhiRegisterAPI=wpc-mdf.jhi.url.createUrl
JhiUpdateAPI=wpc-mdf.jhi.url.updateUrl
JhiFetchAPI=wpc-mdf.jhi.url.readUrl
Lob=wpc-mdf.jhi.lob
ContactEmail=wpc-mdf.jhi.contact
hubble.publisher.frequency=mdf.hubble.properties.publisher.frequency
hubble.publisher.frequency.entity=mdf.hubble.properties.publisher.frequency.entity
hubble.publisher.publish=mdf.hubble.publisher.publish
isHubbleEnabled=mdf.hubble.enabled
hubble.event.names=mdf.hubble.properties.event.names
hubble.publisher.tcp.server.url=wpc-mdf.publisher.tcp.server.url
MDF_A3_KEY_=mdf.idms.target.app-key
APP_ID=mdf.idms.app-id
APP_PASSWORD=mdf.auth.a3.password
OTHER_APP_ID=mdf.idms.target-apps.app-id
CONTEXT=mdf.idms.target-apps.context
